### ISSUE TITLE
npm or yarn?

### ISSUE THREAD

**Issue by hardik-vala** [hardik-vala/TreeSum#16]
The repository contains both a `package-lock.json` and `yarn.lock`, and that's resulting in confusion, e.g.,

<img width="451" alt="Screenshot 2024-01-17 at 17 07 12" src="https://github.com/hardik-vala/TreeSum/assets/2627338/da90a990-a95f-4a15-8a88-fd5f73edc468">

@legalcodes Can we choose one package management solution? I don't care which.

**Comment by legalcodes** [comment]
No problem. I'm removing `yarn.lock` in https://github.com/hardik-vala/TreeSum/pull/19
